### PR TITLE
Tile API changes to support more efficient tile access

### PR DESCRIPTION
**Pull request by jmorton**

### CODE REVIEW

**Comment by oubiwann** [comment]
Looks like there are some conflicts here -- can you fix and push the updates?

**Comment by oubiwann** [comment]
Also, looks like this branch was based on the one that just got merged. Could you rebase after you fix the conflicts?

**Comment by jmorton** [comment]
This branch should not be merged; there is only one small change that needs to be made to the get-tile function.

**Comment by oubiwann** [comment]
Oh, sweet -- that makes it easy!

**Pull request closed without merging**
